# Generated by Django 5.1.4 on 2025-01-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField(max_length=15)),
                ('salary', models.IntegerField(max_length=10)),
                ('dno', models.IntegerField()),
            ],
        ),
    ]
